services:
  elasticsearch-master-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch-master-1
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - elasticsearch_master_1:/usr/share/elasticsearch
    configs:
      - source: elasticsearch_master_1_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    expose:
      - "9200"
      - "9300"
    ports:
      - "9200:9200"
    networks:
      - elk
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '1'

  elasticsearch-data-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch-data-1
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - elasticsearch_data_1:/usr/share/elasticsearch
    configs:
      - source: elasticsearch_data_1_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    expose:
      - "9200"
      - "9300"
    networks:
      - elk
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '1'

  elasticsearch-data-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch-data-2
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - elasticsearch_data_2:/usr/share/elasticsearch
    configs:
    - source: elasticsearch_data_2_config
      target: /usr/share/elasticsearch/config/elasticsearch.yml
    expose:
      - "9200"
      - "9300"
    networks:
      - elk
    deploy:
      resources:
        limits:
          memory: 1g

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.2
    container_name: kibana
    volumes:
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    expose:
      - "5601"
    ports:
      - "5601:5601"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.2
    container_name: logstash
    volumes:
      - ./config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./config/logstash/pipeline.conf:/usr/share/logstash/pipeline/pipeline.conf
    expose:
      - "5044"
    networks:
      - elk

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   volumes:
  #     - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   expose:
  #     - "9090"
  #   networks:
  #     - elk

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   volumes:
  #     - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
  #   expose:
  #     - "3000"
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - elk

networks:
  elk:
    name: elk
  
volumes:
  elasticsearch_master_1:
    driver: local
  elasticsearch_data_1:
    driver: local
  elasticsearch_data_2:
    driver: local

configs:
  elasticsearch_master_1_config:
    file: ./config/elasticsearch/master-1/elasticsearch.yml
  elasticsearch_data_1_config:
    file: ./config/elasticsearch/data-1/elasticsearch.yml
  elasticsearch_data_2_config:
    file: ./config/elasticsearch/data-2/elasticsearch.yml
  
